// Beholder validator constant tables — vendored verbatim from the Beholder
// reference extractor (GetBeholder/Beholder-ME, AGPL-3.0-only), which generates
// them from the datagen validator. Data only: never hand-edit a value. To update,
// regenerate from the source and re-run Prettier — the formatting here is the
// repository's, the content is the generator's.
/* eslint-disable */

export const DAMAGE_ENUM = ["broken", "damaged", "pristine"];
export const SEVERITY_ENUM = ["critical", "minor", "serious"];
export const VALID_SLOTS = [
  "back",
  "chest",
  "face",
  "head",
  "hind_left_foot",
  "hind_left_leg",
  "hind_right_foot",
  "hind_right_leg",
  "left_arm",
  "left_ear",
  "left_eye",
  "left_foot",
  "left_hand",
  "left_leg",
  "left_shoulder",
  "mouth",
  "neck",
  "right_arm",
  "right_ear",
  "right_eye",
  "right_foot",
  "right_hand",
  "right_leg",
  "right_shoulder",
  "tail",
  "waist",
];
export const NO_WORN_DAMAGE_SLOTS = ["left_ear", "mouth", "right_ear"];
export const PROXIMAL_OF = {
  left_arm: ["left_shoulder"],
  left_hand: ["left_shoulder", "left_arm"],
  right_arm: ["right_shoulder"],
  right_hand: ["right_shoulder", "right_arm"],
  left_foot: ["left_leg"],
  right_foot: ["right_leg"],
  hind_left_foot: ["hind_left_leg"],
  hind_right_foot: ["hind_right_leg"],
};
export const PASS_BY_BODY_FIELD = {
  worn: "worn",
  wounds: "wounds",
  holding: "holding",
  bare: "flags",
  missing: "flags",
};
export const SPECIES_NO_LEGS = [
  "lamia",
  "merfolk",
  "mermaid",
  "merman",
  "naga",
  "selkie",
  "siren",
  "slime",
  "tritonkin",
];
export const STANDARD_LEG_SLOTS = ["left_foot", "left_leg", "right_foot", "right_leg"];
export const SPECIES_QUADRUPED = [
  "arachne",
  "centaur",
  "colt",
  "dragon",
  "dragoness",
  "drake",
  "drider",
  "driderkin",
  "equine",
  "filly",
  "foal",
  "hivewing",
  "horse",
  "icewing",
  "lamia-taur",
  "leafwing",
  "mare",
  "mudwing",
  "mustang",
  "nightwing",
  "palomino",
  "pony",
  "rainwing",
  "sandwing",
  "seawing",
  "silkwing",
  "skywing",
  "stallion",
  "taur",
  "wyrm",
  "wyrmling",
];
export const HIND_LEG_SLOTS = ["hind_left_foot", "hind_left_leg", "hind_right_foot", "hind_right_leg"];
export const HIND_TO_REGULAR = {
  hind_left_leg: "left_leg",
  hind_right_leg: "right_leg",
  hind_left_foot: "left_foot",
  hind_right_foot: "right_foot",
};
export const MULTI_SLOT_TABLE = {
  boots: ["left_foot", "right_foot"],
  shoes: ["left_foot", "right_foot"],
  sandals: ["left_foot", "right_foot"],
  heels: ["left_foot", "right_foot"],
  sneakers: ["left_foot", "right_foot"],
  slippers: ["left_foot", "right_foot"],
  loafers: ["left_foot", "right_foot"],
  oxfords: ["left_foot", "right_foot"],
  stilettos: ["left_foot", "right_foot"],
  flats: ["left_foot", "right_foot"],
  platforms: ["left_foot", "right_foot"],
  wedges: ["left_foot", "right_foot"],
  pumps: ["left_foot", "right_foot"],
  trainers: ["left_foot", "right_foot"],
  cleats: ["left_foot", "right_foot"],
  "flip-flops": ["left_foot", "right_foot"],
  "flip flops": ["left_foot", "right_foot"],
  galoshes: ["left_foot", "right_foot"],
  waders: ["left_foot", "right_foot"],
  "snow boots": ["left_foot", "right_foot"],
  geta: ["left_foot", "right_foot"],
  zori: ["left_foot", "right_foot"],
  tabi: ["left_foot", "right_foot"],
  moccasins: ["left_foot", "right_foot"],
  "combat boots": ["left_foot", "right_foot"],
  "magnetic boots": ["left_foot", "right_foot"],
  gloves: ["left_hand", "right_hand"],
  mittens: ["left_hand", "right_hand"],
  gauntlets: ["left_hand", "right_hand"],
  wraps: ["left_hand", "right_hand"],
  "boxing gloves": ["left_hand", "right_hand"],
  "oven mitts": ["left_hand", "right_hand"],
  vambraces: ["left_arm", "right_arm"],
  bracers: ["left_arm", "right_arm"],
  armguards: ["left_arm", "right_arm"],
  "arm guards": ["left_arm", "right_arm"],
  "forearm guards": ["left_arm", "right_arm"],
  pauldrons: ["left_shoulder", "right_shoulder"],
  spaulders: ["left_shoulder", "right_shoulder"],
  "shoulder guards": ["left_shoulder", "right_shoulder"],
  "shoulder pads": ["left_shoulder", "right_shoulder"],
  greaves: ["left_leg", "right_leg"],
  "shin guards": ["left_leg", "right_leg"],
  "shin pads": ["left_leg", "right_leg"],
  sabatons: ["left_foot", "right_foot"],
  glasses: ["left_eye", "right_eye"],
  spectacles: ["left_eye", "right_eye"],
  eyeglasses: ["left_eye", "right_eye"],
  sunglasses: ["left_eye", "right_eye"],
  shades: ["left_eye", "right_eye"],
  goggles: ["left_eye", "right_eye"],
  "reading glasses": ["left_eye", "right_eye"],
  bifocals: ["left_eye", "right_eye"],
  earrings: ["left_ear", "right_ear"],
  "ear cuffs": ["left_ear", "right_ear"],
  "ear studs": ["left_ear", "right_ear"],
  "hoop earrings": ["left_ear", "right_ear"],
  "ear plugs": ["left_ear", "right_ear"],
  "ear gauges": ["left_ear", "right_ear"],
  pants: ["left_leg", "right_leg", "waist"],
  trousers: ["left_leg", "right_leg", "waist"],
  leggings: ["left_leg", "right_leg", "waist"],
  breeches: ["left_leg", "right_leg", "waist"],
  sweatpants: ["left_leg", "right_leg", "waist"],
  jeans: ["left_leg", "right_leg", "waist"],
  slacks: ["left_leg", "right_leg", "waist"],
  "cargo pants": ["left_leg", "right_leg", "waist"],
  khakis: ["left_leg", "right_leg", "waist"],
  chinos: ["left_leg", "right_leg", "waist"],
  joggers: ["left_leg", "right_leg", "waist"],
  shorts: ["left_leg", "right_leg", "waist"],
  capris: ["left_leg", "right_leg", "waist"],
  culottes: ["left_leg", "right_leg", "waist"],
  hakama: ["left_leg", "right_leg", "waist"],
  dhoti: ["left_leg", "right_leg", "waist"],
  "harem pants": ["left_leg", "right_leg", "waist"],
  tights: ["left_leg", "right_leg", "waist"],
  skirt: ["left_leg", "right_leg", "waist"],
  miniskirt: ["left_leg", "right_leg", "waist"],
  kilt: ["left_leg", "right_leg", "waist"],
  sarong: ["left_leg", "right_leg", "waist"],
  lungi: ["left_leg", "right_leg", "waist"],
  "wrap skirt": ["left_leg", "right_leg", "waist"],
  robe: ["back", "chest", "left_leg", "right_leg", "waist"],
  kimono: ["back", "chest", "left_leg", "left_shoulder", "right_leg", "right_shoulder", "waist"],
  yukata: ["back", "chest", "left_leg", "left_shoulder", "right_leg", "right_shoulder", "waist"],
  habit: ["back", "chest", "left_leg", "left_shoulder", "right_leg", "right_shoulder", "waist"],
  cassock: ["back", "chest", "left_leg", "left_shoulder", "right_leg", "right_shoulder", "waist"],
  overalls: ["back", "chest", "left_leg", "left_shoulder", "right_leg", "right_shoulder", "waist"],
  coveralls: ["back", "chest", "left_leg", "left_shoulder", "right_leg", "right_shoulder", "waist"],
  hose: ["left_leg", "right_leg", "waist"],
  stockings: ["left_leg", "right_leg"],
  socks: ["left_foot", "right_foot"],
  "tabi socks": ["left_foot", "right_foot"],
};
export const COLOR_WORDS_FOR_ITEM_CHECK = [
  "amber",
  "apricot",
  "aqua",
  "aquamarine",
  "ash",
  "azure",
  "beige",
  "black",
  "blood red",
  "blood-red",
  "blue",
  "bone white",
  "bone-white",
  "brown",
  "burgundy",
  "cerulean",
  "charcoal",
  "chartreuse",
  "cobalt",
  "cream",
  "crimson",
  "cyan",
  "dark blue",
  "dark green",
  "dark red",
  "dark-blue",
  "dark-red",
  "deep blue",
  "deep red",
  "deep-blue",
  "deep-red",
  "emerald",
  "forest green",
  "forest-green",
  "fuchsia",
  "gold",
  "golden",
  "gray",
  "green",
  "grey",
  "indigo",
  "ivory",
  "jet black",
  "jet-black",
  "khaki",
  "khaki green",
  "khaki-green",
  "lavender",
  "light blue",
  "light green",
  "light-blue",
  "lilac",
  "lime",
  "magenta",
  "maroon",
  "mauve",
  "midnight blue",
  "midnight-blue",
  "mint",
  "mustard",
  "navy",
  "ocher",
  "ochre",
  "off-white",
  "olive",
  "orange",
  "pale blue",
  "pale pink",
  "peach",
  "pink",
  "pitch black",
  "pitch-black",
  "plum",
  "purple",
  "red",
  "rose",
  "royal blue",
  "rust",
  "saffron",
  "sapphire",
  "scarlet",
  "sea green",
  "sea-green",
  "sepia",
  "sienna",
  "sky blue",
  "sky-blue",
  "slate",
  "snow white",
  "snow-white",
  "tan",
  "taupe",
  "teal",
  "turquoise",
  "umber",
  "vermilion",
  "vermillion",
  "violet",
  "white",
  "wine red",
  "wine-red",
  "yellow",
];
export const ITEM_CATEGORIES = {
  bag: {
    items: [
      "backpack",
      "bag",
      "belt bag",
      "briefcase",
      "bum bag",
      "clutch",
      "duffel",
      "duffel bag",
      "duffle",
      "duffle bag",
      "fanny pack",
      "go-bag",
      "handbag",
      "haversack",
      "hip pack",
      "kit bag",
      "knapsack",
      "messenger bag",
      "pouch",
      "purse",
      "rucksack",
      "saddlebag",
      "satchel",
      "shoulder bag",
      "sling",
      "sling bag",
      "tactical bag",
      "tote",
      "tote bag",
    ],
    allowed_slots: ["back", "left_shoulder", "right_shoulder", "waist"],
    paired_slots: [],
    severity: "warning",
    fix_hint:
      "Bags are HELD (move to holding pass) OR strapped over a shoulder/back/waist. NEVER on chest, face, head, eye, etc. Most casual bags belong in holding; over-the-shoulder bags go on left_shoulder/right_shoulder; backpacks/rucksacks on back.",
  },
  wristwear: {
    items: [
      "apple watch",
      "arm band",
      "armband",
      "armlet",
      "bangle",
      "bracelet",
      "cuff",
      "fitbit",
      "fitness tracker",
      "smartwatch",
      "watch",
      "wrist cuff",
      "wristband",
      "wristwatch",
    ],
    allowed_slots: ["left_arm", "right_arm"],
    paired_slots: [],
    severity: "warning",
    fix_hint:
      "Wrist/arm items conventionally go on left_arm or right_arm (the schema places the wrist on the arm slot). Hand-mounted devices (sci-fi/cyber) are legitimate; verify against prose.",
  },
  eyewear_paired: {
    items: [
      "bifocals",
      "eyeglasses",
      "glasses",
      "goggles",
      "lorgnette",
      "pince-nez",
      "reading glasses",
      "shades",
      "ski goggles",
      "spectacles",
      "sunglasses",
      "swim goggles",
      "vr goggles",
    ],
    allowed_slots: ["face", "head", "left_eye", "right_eye"],
    paired_slots: [["left_eye", "right_eye"]],
    severity: "warning",
    fix_hint:
      "Glasses/goggles conventionally cover BOTH eyes — emit on left_eye AND right_eye (frame may also rest on 'face' or 'head'). Single-eye cybernetic implants / magical lenses exist; verify against prose.",
  },
  eyewear_single: {
    items: ["eye patch", "eyepatch", "monocle"],
    allowed_slots: ["left_eye", "right_eye"],
    paired_slots: [],
    severity: "warning",
    fix_hint: "Monocles/eyepatches conventionally go on one eye slot.",
  },
  rings: {
    items: ["engagement ring", "knuckle ring", "promise ring", "ring", "signet ring", "thumb ring", "wedding ring"],
    allowed_slots: ["left_hand", "right_hand"],
    paired_slots: [],
    severity: "warning",
    fix_hint:
      "Rings conventionally go on left_hand or right_hand. Ring-on-chain (worn around the neck) is legitimate — keep on neck slot with item='ring on chain' or similar.",
  },
  neckwear: {
    items: [
      "amulet",
      "ascot",
      "bandanna around neck",
      "bow tie",
      "bowtie",
      "chain",
      "choker",
      "collar",
      "cravat",
      "locket",
      "muffler",
      "neckerchief",
      "necklace",
      "necktie",
      "pendant",
      "scapular",
      "scarf",
      "tie",
      "torc",
      "torque",
    ],
    allowed_slots: ["neck"],
    paired_slots: [],
    severity: "warning",
    fix_hint:
      "Necklaces, pendants, ties, scarves conventionally go on the 'neck' slot. A very long pendant resting on chest is legitimate — verify against prose before changing.",
  },
  earwear: {
    items: [
      "ear cuff",
      "ear cuffs",
      "ear gauge",
      "ear gauges",
      "ear hoop",
      "ear hoops",
      "ear plug",
      "ear plugs",
      "ear stud",
      "ear studs",
      "earring",
      "earrings",
      "hoop earring",
      "hoop earrings",
      "stud earring",
    ],
    allowed_slots: ["left_ear", "right_ear"],
    paired_slots: [["left_ear", "right_ear"]],
    severity: "warning",
    fix_hint:
      "Earrings conventionally go on left_ear/right_ear. Earrings worn as a PAIR (plural in prose) usually appear on BOTH ears.",
  },
  headwear: {
    items: [
      "ballcap",
      "bandana",
      "bandanna",
      "baseball cap",
      "beanie",
      "boater",
      "bowler",
      "cap",
      "circlet",
      "crown",
      "diadem",
      "fedora",
      "fez",
      "hat",
      "head band",
      "headband",
      "helm",
      "helmet",
      "hood",
      "kerchief",
      "kippah",
      "kufi",
      "panama hat",
      "tam",
      "tam-o-shanter",
      "tiara",
      "top hat",
      "tophat",
      "toque",
      "trilby",
      "turban",
      "ushanka",
      "yarmulke",
    ],
    allowed_slots: ["head"],
    paired_slots: [],
    severity: "warning",
    fix_hint:
      "Hats, helmets, hoods, headbands conventionally go on the 'head' slot. Symbolic gestures (hat held to chest in mourning) belong in the holding pass, not worn.",
  },
  headwear_face_overlap: {
    items: ["balaclava", "executioner's hood", "ski mask", "veil"],
    allowed_slots: ["face", "head"],
    paired_slots: [],
    severity: "warning",
    fix_hint:
      "Veils/balaclavas cover head AND face — emit on both slots if the prose describes full coverage; head OR face alone is acceptable for partial coverage.",
  },
  gloves: {
    items: [
      "boxing glove",
      "boxing gloves",
      "fingerless glove",
      "fingerless gloves",
      "gauntlet",
      "gauntlets",
      "glove",
      "gloves",
      "mitt",
      "mitten",
      "mittens",
      "mitts",
      "tactical glove",
      "tactical gloves",
    ],
    allowed_slots: ["left_hand", "right_hand"],
    paired_slots: [["left_hand", "right_hand"]],
    severity: "warning",
    fix_hint:
      "Gloves/mittens/gauntlets conventionally go on left_hand AND right_hand. One-handed (e.g. magic-using hand, one-armed character, single fingerless glove) is legitimate — verify against prose.",
  },
  footwear: {
    items: [
      "ankle boot",
      "ankle boots",
      "boot",
      "boots",
      "combat boot",
      "combat boots",
      "flip-flop",
      "flip-flops",
      "flipflops",
      "geta",
      "heel",
      "heels",
      "high heel",
      "high heels",
      "knee-high boot",
      "knee-high boots",
      "loafer",
      "loafers",
      "moccasin",
      "moccasins",
      "pump",
      "pumps",
      "sandal",
      "sandals",
      "shoe",
      "shoes",
      "slipper",
      "slippers",
      "sneaker",
      "sneakers",
      "sock",
      "socks",
      "stocking",
      "stockings",
      "tabi",
      "thigh-high boot",
      "thigh-high boots",
      "trainer",
      "trainers",
      "work boot",
      "work boots",
      "zori",
    ],
    allowed_slots: ["hind_left_foot", "hind_right_foot", "left_foot", "right_foot"],
    paired_slots: [["left_foot", "right_foot"]],
    severity: "warning",
    fix_hint:
      "Footwear conventionally goes on left_foot AND right_foot. Single-foot wear (lost boot, prosthetic) is legitimate — verify.",
  },
  legwear_lower: {
    items: [
      "breeches",
      "culottes",
      "dhoti",
      "hakama",
      "jeans",
      "joggers",
      "khakis",
      "kilt",
      "leggings",
      "lungi",
      "maxi skirt",
      "midi skirt",
      "miniskirt",
      "pantaloons",
      "pants",
      "sarong",
      "shorts",
      "skirt",
      "skort",
      "slacks",
      "sweatpants",
      "tights",
      "tracksuit bottoms",
      "trousers",
    ],
    allowed_slots: ["hind_left_leg", "hind_right_leg", "left_leg", "right_leg", "waist"],
    paired_slots: [["left_leg", "right_leg"]],
    severity: "warning",
    fix_hint:
      "Pants/skirts/trousers conventionally cover both legs (and anchor at the waist). Emit on left_leg AND right_leg, plus 'waist' if the prose emphasizes the waistband. Asymmetric garments (single pant-leg, harem-style) are legitimate — verify.",
  },
  waistwear: {
    items: [
      "belt",
      "cummerbund",
      "garter belt",
      "girdle",
      "money belt",
      "obi",
      "sash",
      "sword belt",
      "tool belt",
      "utility belt",
      "weapon belt",
    ],
    allowed_slots: ["waist"],
    paired_slots: [],
    severity: "warning",
    fix_hint:
      "Belts/sashes conventionally go on the 'waist' slot. Baldrics (strap-across-chest weapon belts) are legitimate on chest/back — verify against prose.",
  },
  vambraces: {
    items: [
      "arm guard",
      "arm guards",
      "armguard",
      "armguards",
      "bracer",
      "bracers",
      "forearm guard",
      "forearm guards",
      "vambrace",
      "vambraces",
    ],
    allowed_slots: ["left_arm", "right_arm"],
    paired_slots: [["left_arm", "right_arm"]],
    severity: "error",
    fix_hint: "Vambraces/bracers are forearm armor: left_arm AND right_arm.",
  },
  pauldrons: {
    items: [
      "pauldron",
      "pauldrons",
      "shoulder armor",
      "shoulder armour",
      "shoulder guard",
      "shoulder guards",
      "shoulder pad",
      "shoulder pads",
      "spaulder",
      "spaulders",
    ],
    allowed_slots: ["left_shoulder", "right_shoulder"],
    paired_slots: [["left_shoulder", "right_shoulder"]],
    severity: "error",
    fix_hint: "Pauldrons/spaulders/shoulder guards go on left_shoulder AND right_shoulder.",
  },
  greaves: {
    items: ["greave", "greaves", "shin armor", "shin armour", "shin guard", "shin guards", "shin pad", "shin pads"],
    allowed_slots: ["hind_left_leg", "hind_right_leg", "left_leg", "right_leg"],
    paired_slots: [["left_leg", "right_leg"]],
    severity: "error",
    fix_hint: "Greaves/shin guards go on left_leg AND right_leg.",
  },
  sabatons: {
    items: [
      "armored boot",
      "armored boots",
      "foot armor",
      "foot armour",
      "metal boot",
      "metal boots",
      "sabaton",
      "sabatons",
    ],
    allowed_slots: ["hind_left_foot", "hind_right_foot", "left_foot", "right_foot"],
    paired_slots: [["left_foot", "right_foot"]],
    severity: "error",
    fix_hint: "Sabatons/foot armor go on left_foot AND right_foot.",
  },
  masks: {
    items: [
      "carnival mask",
      "domino mask",
      "face mask",
      "gas mask",
      "mask",
      "n95",
      "oxygen mask",
      "respirator",
      "ski mask",
      "surgical mask",
    ],
    allowed_slots: ["face"],
    paired_slots: [],
    severity: "warning",
    fix_hint:
      "Masks/respirators conventionally go on the 'face' slot. Pushed up onto the head between uses → head; held in hand → holding.",
  },
  mouthwear: {
    items: ["gag", "lip stud", "muzzle", "tongue piercing", "tongue ring"],
    allowed_slots: ["face", "mouth"],
    paired_slots: [],
    severity: "warning",
    fix_hint: "Mouth/lip items conventionally go on 'mouth' (or 'face' for muzzles).",
  },
};
export const MINOR_DEFAULT_INJURY_NOUNS = [
  "abrasion",
  "bloody nose",
  "bruise",
  "cut",
  "graze",
  "light bruise",
  "light scratch",
  "minor cut",
  "nick",
  "nosebleed",
  "rope burn",
  "rope-burn",
  "scrape",
  "scratch",
  "shallow cut",
  "shallow graze",
  "shallow scratch",
  "skinned knee",
  "small bruise",
  "small cut",
  "small graze",
  "split lip",
  "thin cut",
];
export const SEVERITY_ESCALATORS_PROSE = [
  "agonizing",
  "agony",
  "blackness",
  "blackout",
  "blinding",
  "blinding pain",
  "broken",
  "can not move",
  "can not stand",
  "can't move",
  "can't stand",
  "concussed",
  "concussion",
  "crunch",
  "crunching",
  "deep",
  "deeper",
  "deeply",
  "dislocated",
  "dislocation",
  "eyes rolling",
  "fracture",
  "fractured",
  "fracturing",
  "gushing",
  "intestines",
  "knocked out",
  "limb severed",
  "pouring",
  "rolling back",
  "searing",
  "severed",
  "shatter",
  "shattered",
  "shattering",
  "skull fracture",
  "snap",
  "snapped",
  "soaking",
  "spine",
  "streaming",
  "unconscious",
  "vision blurred",
  "vision narrowing",
  "vision swimming",
  "white-hot",
  "whitehot",
];
export const STRUCTURAL_DAMAGE_CUES = [
  "barely any soles",
  "barely even holding onto",
  "barely holding onto",
  "barely holding together",
  "bent",
  "blunted",
  "blunting",
  "break",
  "breaking",
  "breaks",
  "broken",
  "buckle snapped",
  "buckled",
  "buckles",
  "buckling",
  "burned",
  "burnt",
  "caved in",
  "charred",
  "chip",
  "chipped",
  "chips",
  "crack",
  "cracked",
  "cracking",
  "cracks",
  "crushed",
  "cut",
  "cuts",
  "dent",
  "dented",
  "dents",
  "dulled",
  "falling apart",
  "fell apart",
  "fray",
  "frayed",
  "fraying",
  "fraying seam",
  "gouge",
  "gouged",
  "gouges",
  "holes",
  "loose stitching",
  "melt",
  "melted",
  "melting",
  "melts",
  "missing buckle",
  "patched",
  "patchwork",
  "patchwork of repairs",
  "perforated",
  "pierce",
  "pierced",
  "pierces",
  "piercing",
  "puncture",
  "punctured",
  "punctures",
  "repaired",
  "repairs",
  "rip",
  "ripped",
  "ripping",
  "rips",
  "scorched",
  "score marks",
  "scored",
  "scratch",
  "scratched",
  "scratches",
  "scratching",
  "scuff",
  "scuffed",
  "scuffs",
  "shatter",
  "shattered",
  "shattering",
  "shatters",
  "shred",
  "shredded",
  "shreds",
  "singed",
  "slash",
  "slashed",
  "slice",
  "sliced",
  "snap",
  "snapped",
  "snapping",
  "snaps",
  "sole flapping",
  "sole left",
  "soles left",
  "splintered",
  "split",
  "splits",
  "splitting",
  "strap snapped",
  "strap torn",
  "tattered",
  "tear",
  "tearing",
  "tears",
  "thin as your boots",
  "thin boots",
  "threadbare",
  "torn",
  "unraveled",
  "unraveling",
  "unravelled",
  "unravelling",
  "warp",
  "warped",
  "warping",
  "warps",
  "worn through",
];
export const SOILING_ONLY_CUES = [
  "blood soaked",
  "blood-soaked",
  "blood-streaked",
  "bloodied",
  "bloody",
  "damp",
  "dirtied",
  "dirty",
  "dust caked",
  "dust-caked",
  "dusty",
  "grass-stained",
  "grease-stained",
  "grime",
  "grimy",
  "mud caked",
  "mud-caked",
  "muddy",
  "oil-stained",
  "paint-stained",
  "smeared",
  "smudged",
  "soaked",
  "soot",
  "sooty",
  "stained",
  "sweat soaked",
  "sweat-soaked",
  "sweaty",
  "vomit",
  "waterlogged",
  "wet",
  "wine-stained",
];
export const ARMOR_FORM_PROSE_QUALIFIERS = [
  "ablative",
  "ballistic",
  "breastplate",
  "brigandine",
  "ceramic",
  "chain",
  "chainmail",
  "cuirass",
  "exosuit",
  "gauntlet",
  "gauntlets",
  "gorget",
  "greave",
  "greaves",
  "gunmetal",
  "hardsuit",
  "hauberk",
  "helm",
  "helmet",
  "kevlar",
  "lamellar",
  "laminar",
  "mail",
  "pauldron",
  "pauldrons",
  "plate",
  "power armor",
  "ringed",
  "ringmail",
  "sabatons",
  "scale",
  "scaled",
  "segmented",
  "splint",
  "splinted",
  "studded",
  "tactical",
  "vambrace",
  "vambraces",
  "visor",
];
export const CRITICAL_ESCALATORS = [
  "severed",
  "amputat",
  "bone exposed",
  "exposed bone",
  "bone protrud",
  "compound fracture",
  "arterial",
  "spurting",
  "gushing blood",
  "blood gushed",
  "gush of blood",
  "eviscerat",
  "disembowel",
  "bleeding out",
  "bled out",
  "near-fatal",
  "life-threatening",
  "torn off",
];
export const SLOT_CATEGORY_STRIP = {
  left_hand: [
    "earwear",
    "eyewear_paired",
    "eyewear_single",
    "footwear",
    "headwear",
    "headwear_face_overlap",
    "masks",
    "mouthwear",
  ],
  right_hand: [
    "earwear",
    "eyewear_paired",
    "eyewear_single",
    "footwear",
    "headwear",
    "headwear_face_overlap",
    "masks",
    "mouthwear",
  ],
  left_eye: ["bag", "footwear", "legwear_lower"],
  right_eye: ["bag", "footwear", "legwear_lower"],
  left_ear: ["bag", "footwear", "legwear_lower"],
  right_ear: ["bag", "footwear", "legwear_lower"],
  mouth: ["bag", "footwear", "legwear_lower"],
};
export const WOUND_SLOT_ANATOMY = {
  concussion: ["head"],
  "black eye": ["face", "left_eye", "right_eye"],
  "split lip": ["face", "mouth"],
  "busted lip": ["face", "mouth"],
  "bloody nose": ["face"],
  nosebleed: ["face"],
  "sprained ankle": ["left_foot", "left_leg", "right_foot", "right_leg"],
  "twisted ankle": ["left_foot", "left_leg", "right_foot", "right_leg"],
  "stubbed toe": ["left_foot", "right_foot"],
};
export const SPECIES_REJECT_DESCRIPTORS = [
  "admiral",
  "captain",
  "colonel",
  "corporal",
  "detective",
  "general",
  "inspector",
  "lieutenant",
  "marshal",
  "mudblood",
  "muggle",
  "officer",
  "professor",
  "pureblood",
  "sergeant",
];
export const HOLDING_ADD_CUES = [
  "closed around",
  "closes around",
  "clutched",
  "clutches",
  "drawn",
  "draws",
  "draws out",
  "drew",
  "grabbed",
  "grabs",
  "gripped",
  "grips",
  "picked up",
  "picks up",
  "pulled out",
  "pulls out",
  "scooped up",
  "scoops up",
  "seized",
  "seizes",
  "snatched",
  "snatches",
  "takes hold",
  "takes up",
  "took hold",
  "took up",
  "unsheathed",
  "unsheathes",
  "yanked free",
];
export const WORN_DON_CUES = [
  "buttoned up",
  "buttons up",
  "changes into",
  "donned",
  "donning",
  "dons",
  "draws on",
  "dressed in",
  "dresses in",
  "drew on",
  "fastened",
  "fastens",
  "fits",
  "fitted",
  "laced up",
  "laces up",
  "lowered the hood",
  "lowers the hood",
  "pulled on",
  "pulled over her head",
  "pulled over his head",
  "pulled up over",
  "pulling on",
  "pulls on",
  "pulls over her head",
  "pulls over his head",
  "put it on",
  "put on",
  "puts it on",
  "puts on",
  "putting on",
  "raised the hood",
  "raises the hood",
  "slipped into",
  "slipped on",
  "slips into",
  "slips on",
  "snapped on",
  "snaps on",
  "steps into",
  "swapped for",
  "swaps for",
  "switches to",
  "threw on",
  "throws it on",
  "throws on",
  "tied on",
  "ties on",
  "wears a fresh",
  "wears a new",
  "wrapped a",
  "wrapped the",
  "wraps a",
  "wraps the",
  "zipped up",
  "zips up",
];
export const HAND_WORN_STAPLES = [
  "bandage",
  "bandages",
  "brace",
  "cast",
  "mitt",
  "mitts",
  "sling",
  "tape",
  "wrap",
  "wraps",
];
export const INTERACTION_CUE_PHRASES = [
  "fiddled with",
  "fiddles with",
  "fiddling with",
  "finger along",
  "finger brushes",
  "finger traces",
  "reached for",
  "reaches for",
  "reaches toward",
  "reaching for",
  "reaching toward",
  "rested a hand on",
  "rests a hand on",
  "rests her hand on",
  "rests his hand on",
  "thumb along",
  "thumb brushes",
  "thumb finds",
  "thumb traces",
];
export const MUTEX_GARMENT_CLASSES = {
  body_armor: [
    "aketon",
    "ballistic vest",
    "banded mail",
    "body armor",
    "body armour",
    "breastplate",
    "brigandine",
    "bulletproof vest",
    "chain mail",
    "chainmail",
    "combat armor",
    "corselet",
    "cuirass",
    "flak jacket",
    "full plate",
    "gambeson",
    "half plate",
    "half-plate",
    "hauberk",
    "kevlar vest",
    "lamellar",
    "leather armor",
    "leather armour",
    "plackart",
    "plate armor",
    "plate armour",
    "plate carrier",
    "plate mail",
    "power armor",
    "power armour",
    "ring mail",
    "riot armor",
    "scale armor",
    "scale armour",
    "scale mail",
    "splint mail",
    "studded leather",
  ],
};

// ── Canonical garment identity table (plural -> singular) ──
// Regenerate: python3 scripts/dump_garment_canon.py > ../Beholder/garment_data.js (source = datagen).
// Plural→singular garment-identity aliases so 'boot' and 'boots' are ONE identity.
// The runtime only does GARMENT_CANON[x] ?? x; see state.js canonicalGarment().

export const GARMENT_CANON = {
  boots: "boot",
  "boxing shoes": "boxing shoe",
  bracers: "bracer",
  greaves: "greave",
  heels: "heel",
  pauldrons: "pauldron",
  sandals: "sandal",
  shoes: "shoe",
  slippers: "slipper",
  sneakers: "sneaker",
  stockings: "stocking",
  trousers: "trouser",
};
